PAIRS = [
    ("yıkama", "yıkama"),
    ("tablet", "tablet"),
    ("kapsül", "tablet"),
    ("litre", "lt"),
    ("tane", "adet"),
    ("adet", "adet"),
    ("ml", "ml"),
    ("cc", "ml"),
    ("cl", "cl"),
    ("lt", "lt"),
    ("gr", "gr"),
    ("kg", "kg"),
    ("mg", "mg"),
    ("lı", "adet"),
    ("li", "adet"),
    ("lu", "adet"),
    ("lü", "adet"),
    ("g", "gr"),
    ("l", "lt"),
]
